name: Entrenamiento de modelos

on:
  push:
    branches:
      - certification
    paths:
      - "MLOps-InsightLab/src/model_training.py"
      - "MLOps-InsightLab/src/ft_engineering.py"

  pull_request:
    branches:
      - certification
      - main
    paths:
      - "MLOps-InsightLab/src/model_training.py"
      - "MLOps-InsightLab/src/ft_engineering.py"
      
jobs:
  train-models:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: MLOps-InsightLab

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v6

      - name: Configurar Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar entrenamiento de modelos
        run: |
          python src/model_training.py
